"use client";

import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { useState, type ComponentType } from "react";
import { Bell, BriefcaseBusiness, Check, ChevronLeft, ChevronRight, ClipboardList, Ellipsis, FileText, Gauge, Heart, LayoutDashboard, Menu, MessageSquare, Network, Plus, Search, Settings, SlidersHorizontal, Sparkles, Users, X } from "lucide-react";

type Role = "applicant" | "employee" | "recruiter" | "admin";
type Item = { label: string; href: string; icon: ComponentType<{ className?: string }> };
const icons = { dashboard: LayoutDashboard, jobs: BriefcaseBusiness, referrals: Network, saved: Heart, bell: Bell, message: MessageSquare, users: Users, pipeline: Gauge, settings: Settings, activity: ClipboardList, reports: FileText, preferences: SlidersHorizontal };
const nav: Record<Role, Item[]> = {
  applicant: [{ label: "Dashboard", href: "/dashboard", icon: icons.dashboard }, { label: "Jobs", href: "/jobs", icon: icons.jobs }, { label: "Referral requests", href: "/referrals", icon: icons.referrals }, { label: "Saved jobs", href: "/saved-jobs", icon: icons.saved }, { label: "Notifications", href: "/notifications", icon: icons.bell }, { label: "Messages", href: "/messages", icon: icons.message }],
  employee: [{ label: "Dashboard", href: "/dashboard", icon: icons.dashboard }, { label: "Referral requests", href: "/referral-requests", icon: icons.referrals }, { label: "My referrals given", href: "/my-referrals-given", icon: icons.referrals }, { label: "Jobs", href: "/jobs", icon: icons.jobs }, { label: "Referral preferences", href: "/referral-preferences", icon: icons.preferences }, { label: "Notifications", href: "/notifications", icon: icons.bell }],
  recruiter: [{ label: "Dashboard", href: "/dashboard", icon: icons.dashboard }, { label: "Manage jobs", href: "/jobs/manage", icon: icons.jobs }, { label: "Candidates", href: "/candidates", icon: icons.users }, { label: "Pipeline", href: "/pipeline", icon: icons.pipeline }, { label: "Referrals", href: "/referrals", icon: icons.referrals }, { label: "Notifications", href: "/notifications", icon: icons.bell }],
  admin: [{ label: "Dashboard", href: "/admin", icon: icons.dashboard }, { label: "Users", href: "/admin/users", icon: icons.users }, { label: "Jobs", href: "/admin/jobs", icon: icons.jobs }, { label: "Referrals", href: "/admin/referrals", icon: icons.referrals }, { label: "Activity", href: "/admin/activity", icon: icons.activity }, { label: "Reports", href: "/admin/reports", icon: icons.reports }],
};
const roleNames: Record<Role, string> = { applicant: "Applicant", employee: "Employee", recruiter: "Recruiter", admin: "Admin" };
const jobs = [{ title: "Senior Product Designer", company: "Northstar Labs", location: "Bengaluru · Hybrid", referrals: 4, skill: "92% match" }, { title: "Frontend Engineer", company: "Arcade Systems", location: "Remote · India", referrals: 2, skill: "88% match" }, { title: "Data Analyst", company: "Pine & Co.", location: "Mumbai · On-site", referrals: 6, skill: "81% match" }, { title: "Product Manager", company: "Nexora", location: "Bengaluru · Hybrid", referrals: 3, skill: "76% match" }];
const people = ["Ananya Rao", "Maya Chen", "Ishaan Kapoor", "Leo Martin"];

export default function TrustHireApp() {
  const pathname = usePathname(); const query = useSearchParams(); const initial = query.get("role");
  const [role, setRole] = useState<Role>(initial === "employee" || initial === "recruiter" || initial === "admin" ? initial : "applicant");
  const [drawer, setDrawer] = useState(false); const [open, setOpen] = useState(true); const [notice, setNotice] = useState(3);
  const currentNav = nav[role].map(item => ({ ...item, href: withRole(item.href, role) }));
  const title = pageTitle(pathname, role);
  return <div className="min-h-screen bg-[#f7fafb] text-slate-800"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-slate-200 bg-white md:flex"><Sidebar pathname={pathname} role={role} items={currentNav} /></aside>{drawer && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-900/30" onClick={() => setDrawer(false)} /><aside className="relative flex h-full w-[86%] max-w-xs flex-col bg-white shadow-2xl"><Sidebar pathname={pathname} role={role} items={currentNav} onNavigate={() => setDrawer(false)} /></aside></div>}<div className="md:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="grid size-9 place-items-center rounded-md hover:bg-slate-100 md:hidden" onClick={() => setDrawer(true)}><Menu className="size-5" /></button><div><p className="text-sm font-semibold">{title}</p><p className="hidden text-xs text-slate-400 lg:block">{role === "admin" ? "Platform management" : "Your TrustHire workspace"}</p></div></div><div className="flex items-center gap-2"><div className="hidden h-9 w-64 items-center gap-2 rounded-md border border-slate-200 bg-slate-50 px-3 lg:flex"><Search className="size-4 text-slate-400" /><span className="text-xs text-slate-400">Search workspace</span></div><button aria-label="Notifications" className="relative grid size-9 place-items-center rounded-md hover:bg-slate-100" onClick={() => setNotice(0)}><Bell className="size-5" />{notice > 0 && <span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-rose-500" />}</button><div className="grid size-8 place-items-center rounded-full bg-sky-100 text-xs font-bold text-sky-700">AR</div></div></header><main className="mx-auto max-w-[1560px] px-4 py-6 pb-24 sm:px-6 lg:px-8"><RolePreview role={role} setRole={setRole} />{renderPage(pathname, role, open, setOpen)}</main><MobileTabs items={currentNav} pathname={pathname} /></div></div>;
}

function Sidebar({ pathname, role, items, onNavigate }: { pathname: string; role: Role; items: Item[]; onNavigate?: () => void }) { return <><div className="flex h-16 items-center gap-2 px-5"><span className="grid size-8 place-items-center rounded-md bg-primary text-sm font-bold text-white">T</span><span className="font-semibold tracking-tight">TrustHire</span></div><div className="mx-3 flex items-center gap-2 rounded-md bg-slate-50 px-3 py-2 text-sm text-slate-400"><Search className="size-4" />Search <kbd className="ml-auto text-[10px]">⌘K</kbd></div><nav className="mt-5 flex-1 px-3">{items.map(({ label, href, icon: Icon }) => { const active = pathname === href.split("?")[0] || (label === "Dashboard" && pathname === "/dashboard"); return <Link key={label} onClick={onNavigate} href={href} className={`relative mb-1 flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium ${active ? "bg-sky-50 text-primary before:absolute before:-left-3 before:h-6 before:w-[3px] before:bg-primary" : "text-slate-600 hover:bg-slate-50"}`}><Icon className="size-[18px]" />{label}{label === "Notifications" && <span className="ml-auto size-2 rounded-full bg-rose-500" />}</Link> })}</nav><div className="border-t border-slate-100 p-3"><Link href={withRole("/settings", role)} onClick={onNavigate} className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-slate-600 hover:bg-slate-50"><Settings className="size-[18px]" />Settings</Link><Link href={withRole("/profile", role)} onClick={onNavigate} className="mt-2 flex items-center gap-3 rounded-md p-2 hover:bg-slate-50"><span className="grid size-9 place-items-center rounded-full bg-sky-100 text-xs font-bold text-sky-700">AR</span><span><b className="block text-sm">Aarav Rao</b><small className="text-xs text-slate-500">{roleNames[role]}</small></span></Link></div></> }
function RolePreview({ role, setRole }: { role: Role; setRole: (role: Role) => void }) { return <div className="mb-5 flex items-center justify-between gap-3 rounded-md border border-sky-100 bg-sky-50/60 px-3 py-2 text-xs text-slate-600"><span>UI preview role</span><select aria-label="Preview role" value={role} onChange={e => setRole(e.target.value as Role)} className="rounded border border-sky-200 bg-white px-2 py-1 font-medium text-slate-700"><option value="applicant">Applicant</option><option value="employee">Employee</option><option value="recruiter">Recruiter</option><option value="admin">Admin</option></select></div> }
function MobileTabs({ items, pathname }: { items: Item[]; pathname: string }) { return <nav className="fixed inset-x-0 bottom-0 z-30 flex h-16 justify-around border-t border-slate-200 bg-white md:hidden">{items.slice(0, 5).map(({ label, href, icon: Icon }) => <Link key={label} href={href} className={`grid flex-1 place-items-center text-[10px] ${pathname === href.split("?")[0] ? "text-primary" : "text-slate-500"}`}><span className="grid gap-1 text-center"><Icon className="mx-auto size-5" />{label.split(" ")[0]}</span></Link>)}</nav> }
function Stat({ label, value, note, emphasis }: { label: string; value: string; note: string; emphasis?: boolean }) { return <div className={`border p-4 ${emphasis ? "border-sky-200 bg-sky-50" : "border-slate-200 bg-white"}`}><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div> }
function Card({ title, action, children, className = "" }: { title?: string; action?: string; children: React.ReactNode; className?: string }) { return <section className={`border border-slate-200 bg-white ${className}`}><div className={title ? "flex items-center justify-between border-b border-slate-100 px-5 py-4" : ""}>{title && <h2 className="text-sm font-semibold">{title}</h2>}{action && <button className="text-xs font-semibold text-primary">{action}</button>}</div><div className="p-5">{children}</div></section> }
function Badge({ children, type = "pending" }: { children: React.ReactNode; type?: string }) { const styles: Record<string, string> = { pending: "border-amber-200 bg-amber-50 text-amber-700", accepted: "border-emerald-200 bg-emerald-50 text-emerald-700", progress: "border-sky-200 bg-sky-50 text-sky-700", hired: "border-indigo-200 bg-indigo-50 text-indigo-700", rejected: "border-rose-200 bg-rose-50 text-rose-700", role: "border-violet-200 bg-violet-50 text-violet-700" }; return <span className={`inline-flex rounded-full border px-2 py-0.5 text-xs font-medium ${styles[type] || styles.pending}`}>{children}</span> }
function JobCard({ job }: { job: typeof jobs[number] }) { return <Card className="group"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-md bg-slate-100 text-sm font-bold text-slate-600">{job.company[0]}</span><button aria-label="Save job" className="text-slate-400 hover:text-primary"><Heart className="size-5" /></button></div><h3 className="mt-5 font-semibold">{job.title}</h3><p className="mt-1 text-sm text-slate-500">{job.company} · {job.location}</p><div className="mt-4 flex flex-wrap gap-1.5"><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">Full-time</span><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">Mid-level</span></div><div className="mt-4 flex items-center gap-2 rounded-md bg-teal-50 px-2.5 py-2 text-xs font-medium text-teal-700"><Network className="size-4" />{job.referrals} employees can refer you</div><div className="mt-5 flex items-center justify-between text-xs"><span className="text-slate-400">{job.skill}</span><Link href="/jobs/1" className="font-semibold text-primary">View <ChevronRight className="inline size-3" /></Link></div></Card> }

function renderPage(path: string, role: Role, open: boolean, setOpen: (value: boolean) => void) {
  if (path === "/dashboard" || path === "/admin") return <Dashboard role={path === "/admin" ? "admin" : role} open={open} setOpen={setOpen} />;
  if (path === "/jobs") return <Jobs role={role} />;
  if (path.startsWith("/jobs/") && path.includes("employees")) return <Employees />;
  if (path.startsWith("/jobs/")) return <JobDetail />;
  if (["/referrals", "/referral-requests", "/my-referrals-given"].includes(path)) return <Referrals role={role} />;
  if (path === "/pipeline") return <Pipeline />;
  if (path === "/candidates") return <Candidates />;
  if (path === "/jobs/manage/new" || path.endsWith("/edit")) return <JobForm edit={path.endsWith("/edit")} />;
  if (path === "/jobs/manage" || path === "/admin/jobs") return <ManageJobs admin={path === "/admin/jobs"} />;
  if (path === "/admin/users") return <AdminUsers />;
  if (path === "/admin/referrals") return <Referrals role="admin" />;
  if (path === "/admin/activity") return <Activity />;
  if (path === "/admin/reports") return <Reports />;
  if (path === "/notifications") return <Notifications />;
  if (path.startsWith("/profile/")) return <EmployeeProfile />;
  if (path === "/profile") return <Profile role={role} />;
  if (path === "/saved-jobs") return <SavedJobs />;
  if (path === "/messages") return <Messages />;
  if (["/referral-preferences", "/settings"].includes(path)) return <SettingsPage preferences={path === "/referral-preferences"} />;
  return <Empty />;
}
function Dashboard({ role, open, setOpen }: { role: Role; open: boolean; setOpen: (value: boolean) => void }) { if (role === "employee") return <EmployeeDashboard open={open} setOpen={setOpen} />; if (role === "recruiter") return <RecruiterDashboard />; if (role === "admin") return <AdminDashboard />; return <ApplicantDashboard />; }
function ApplicantDashboard() { return <div className="space-y-6"><PageHead eyebrow="Applicant workspace" heading="Welcome back, Aarav" copy="You have 2 referral requests awaiting a response." action="Discover jobs" href="/jobs" /><div className="border border-sky-100 bg-sky-50 p-4 sm:flex sm:items-center sm:gap-6"><div className="flex-1"><p className="text-sm font-semibold">Your profile is 70% complete</p><div className="mt-2 h-1.5 overflow-hidden bg-sky-100"><div className="h-full w-[70%] bg-primary" /></div><div className="mt-2 flex gap-2"><span className="rounded bg-white px-2 py-1 text-xs text-slate-600">Add skills</span><span className="rounded bg-white px-2 py-1 text-xs text-slate-600">Add experience</span></div></div><Link href="/profile" className="mt-3 inline-block text-sm font-semibold text-primary sm:mt-0">Complete profile</Link></div><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-4">{[["Active requests","04","2 pending"],["Accepted referrals","07","Across 3 companies"],["Jobs saved","12","4 new this week"],["Profile views","28","+12% this month"]].map(([a,b,c]) => <Stat key={a} label={a} value={b} note={c} />)}</div><div className="grid gap-6 xl:grid-cols-[1.8fr_1fr]"><div className="space-y-6"><SectionHead title="Recommended jobs" action="View all" href="/jobs" /><div className="grid gap-4 sm:grid-cols-2">{jobs.slice(0,2).map(job => <JobCard key={job.title} job={job} />)}</div></div><div className="space-y-6"><ReferralSummary /><NotificationsPreview /><Card title="Quick actions"><div className="grid gap-2">{[["Find employees to refer me","/jobs/1/employees"],["Update profile","/profile"],["Browse saved jobs","/saved-jobs"]].map(([label, href]) => <Link key={label} href={href} className="flex items-center justify-between border border-slate-200 px-3 py-2.5 text-sm font-medium hover:bg-slate-50">{label}<ChevronRight className="size-4 text-slate-400" /></Link>)}</div></Card></div></div></div> }
function EmployeeDashboard({ open, setOpen }: { open: boolean; setOpen: (value: boolean) => void }) { const [requests, setRequests] = useState(["Maya Chen", "Rohan Desai"]); return <div className="space-y-6"><PageHead eyebrow="Employee workspace" heading="Welcome back, Aarav" copy="Two applicants are waiting for your review." extra={<button onClick={() => setOpen(!open)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${open ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}><span className={`mr-1 inline-block size-1.5 rounded-full ${open ? "bg-emerald-500" : "bg-slate-400"}`} />{open ? "Open to refer" : "Not available"}</button>} /><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-4"><Stat emphasis label="Pending requests" value={String(requests.length).padStart(2,"0")} note="Needs your attention" /><Stat label="Referrals given" value="18" note="All time" /><Stat label="Acceptance rate" value="94%" note="Responded within 3 days" /><Stat label="This month" value="06" note="Referral activities" /></div><Card title="Requests needing your attention" action="Sort: oldest first"><div className="divide-y divide-slate-100">{requests.length ? requests.map((name, i) => <div key={name} className="flex flex-wrap items-center gap-4 py-4 first:pt-0 last:pb-0"><Avatar name={name} /><div className="min-w-48 flex-1"><b className="block text-sm">{name}</b><p className="text-xs text-slate-500">{i ? "Frontend Engineer" : "Senior Product Designer"} · {i ? "Arcade Systems" : "Northstar Labs"}</p><p className="mt-1 text-xs text-slate-400">Product designer with 6 years of experience · Requested 2 days ago</p></div><div className="flex gap-2"><button onClick={() => setRequests(x => x.filter(n => n !== name))} className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-white">Accept</button><button onClick={() => setRequests(x => x.filter(n => n !== name))} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-semibold">Decline</button></div></div>) : <Empty text="You are all caught up." />}</div></Card><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card title="Recent referrals given" action="View all"><ReferralRows /></Card><div className="space-y-6"><Card title="Relevant openings"><div className="space-y-3">{jobs.slice(0,2).map(j => <div key={j.title} className="flex justify-between text-sm"><span><b className="block">{j.title}</b><small className="text-slate-500">{j.company}</small></span><button className="text-xs font-semibold text-primary">Share</button></div>)}</div></Card><NotificationsPreview /></div></div></div> }

function RecruiterDashboard() { return <div className="space-y-6"><PageHead eyebrow="Recruiter workspace" heading="Recruiting overview" copy="A clear view of open roles and candidate progress." action="Post a new job" href="/jobs/manage" /><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-5">{[["Active jobs","12","2 closing soon"],["Total candidates","148","+18 this week"],["Referral candidates","56","38% of total"],["Interviews","14","This week"],["Needs attention","03","Review today"]].map(([a,b,c]) => <Stat key={a} label={a} value={b} note={c} />)}</div><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card title="Hiring pipeline" action="View full pipeline"><div className="space-y-4">{[["Applied",45],["Screening",32],["Interview",18],["Offer",7],["Hired",4]].map(([label, n], i) => <div key={label as string} className="flex items-center gap-3"><span className="w-20 text-xs text-slate-500">{label as string}</span><div className="h-7 flex-1 bg-slate-100"><div className="h-full bg-primary" style={{ width: `${88-i*16}%` }} /></div><b className="w-5 text-xs">{n}</b></div>)}</div></Card><Card title="Jobs needing attention"><div className="space-y-4">{["Platform Engineer","Growth Marketer","QA Lead"].map((job,i) => <div className="flex items-center justify-between" key={job}><span><b className="block text-sm">{job}</b><small className="text-xs text-amber-700">{i===0?"0 applicants":"Closing in 2 days"}</small></span><Link href="/jobs/manage" className="text-xs font-semibold text-primary">Manage</Link></div>)}</div></Card></div><Card title="Recent applicants" action="View candidates"><DataTable columns={["Candidate","Job applied to","Source","Stage","Applied"]} rows={people.slice(0,3).map((p,i) => [p, jobs[i].title, i ? "Direct" : "Referral · Ananya", ["Screening","Interview","Applied"][i], "Today"])} /></Card></div> }
function AdminDashboard() { return <div className="space-y-6"><PageHead eyebrow="Admin workspace" heading="Platform overview" copy="Health, activity and referral outcomes across TrustHire." extra={<select className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs"><option>Last 30 days</option><option>Last 7 days</option></select>} /><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-3 xl:grid-cols-6">{[["Total users","2,480","+42 this week"],["Applicants","1,920","77% of users"],["Employees","412","+8 this week"],["Recruiters","148","19 active"],["Active jobs","186","+12 this week"],["Pending requests","34","5 need review"]].map(([a,b,c]) => <Stat key={a} label={a} value={b} note={c} />)}</div><div className="grid gap-6 lg:grid-cols-2"><Chart title="User growth" labels={["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]} /><Card title="Referral funnel"><div className="space-y-4">{[["Requests sent",340],["Accepted",242],["In progress",164],["Hired",84]].map(([a,b],i) => <div key={a as string}><div className="mb-1 flex justify-between text-xs"><span>{a as string}</span><b>{b}</b></div><div className="h-6 bg-slate-100"><div className="h-full bg-teal-500" style={{width:`${100-i*18}%`}} /></div></div>)}</div></Card></div><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card title="Recent users" action="View all"><DataTable columns={["Name","Role","Company","Joined"]} rows={people.map((p,i) => [p,["Applicant","Employee","Recruiter","Applicant"][i], i === 2 ? "Northstar Labs":"-", "Today"])} /></Card><Card title="Administrative alerts"><div className="space-y-3">{["5 referral requests pending over 7 days","3 jobs have no applicants","2 accounts pending verification"].map(a => <div key={a} className="flex gap-3 border-l-2 border-amber-400 bg-amber-50/50 p-3 text-sm"><span className="flex-1">{a}</span><button className="text-xs font-semibold text-primary">Resolve</button></div>)}</div></Card></div></div> }

function Jobs({ role }: { role: Role }) { return <div className="space-y-6"><PageHead heading={role === "applicant" ? "Discover jobs" : "All jobs"} copy="Find roles where your network can make a difference." action={role === "recruiter" || role === "admin" ? "Post a job" : undefined} href="/jobs/manage" /><div className="flex flex-wrap gap-2 border-y border-slate-200 bg-white p-3"><div className="flex min-w-60 flex-1 items-center gap-2 rounded-md border border-slate-200 px-3 py-2"><Search className="size-4 text-slate-400"/><span className="text-sm text-slate-400">Search jobs, companies, skills</span></div>{["Location","Job type","Experience","Referral available"].map(x => <button key={x} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-medium">{x}</button>)}<button className="grid size-9 place-items-center rounded-md border border-slate-200"><SlidersHorizontal className="size-4"/></button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{jobs.map(j => <JobCard key={j.title} job={j} />)}</div><button className="mx-auto block rounded-md border border-slate-200 bg-white px-4 py-2 text-sm font-medium">Load more jobs</button></div> }
function JobDetail() { return <div className="grid gap-6 xl:grid-cols-[1.9fr_.8fr]"><div className="space-y-6"><div><p className="text-xs text-slate-500">Jobs / Northstar Labs / Senior Product Designer</p><h1 className="mt-4 text-3xl font-semibold tracking-tight">Senior Product Designer</h1><p className="mt-2 text-sm text-slate-500">Northstar Labs · Bengaluru · Hybrid · Full-time</p><p className="mt-5 text-lg font-semibold text-slate-800">₹28L – ₹38L per year</p></div><Card title="About the role"><p className="text-sm leading-7 text-slate-600">Join a thoughtful product team building the hiring infrastructure that helps people make meaningful career moves. You will lead discovery, simplify complex workflows and raise the quality bar across our platform.</p><h3 className="mt-6 text-sm font-semibold">What you will bring</h3><ul className="mt-3 space-y-2 text-sm text-slate-600"><li>• 5+ years designing digital products</li><li>• Strong systems thinking and craft</li><li>• Experience working with product and engineering partners</li></ul></Card><Card title="Skills"><div className="flex flex-wrap gap-2">{["Product design","Figma","Research","Design systems","B2B SaaS"].map(x => <span key={x} className="rounded bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{x}</span>)}</div></Card></div><aside className="h-fit border border-sky-200 bg-white p-5 xl:sticky xl:top-24"><div className="flex items-center gap-2 text-sm font-semibold text-teal-700"><Network className="size-5"/>4 employees can refer you</div><p className="mt-2 text-sm text-slate-500">Meet people at Northstar Labs who are open to making an introduction.</p><Link href="/jobs/1/employees" className="mt-5 block rounded-md bg-primary px-4 py-3 text-center text-sm font-semibold text-white">Request a referral</Link><button className="mt-2 w-full rounded-md border border-slate-200 px-4 py-3 text-sm font-semibold">Apply directly</button><div className="mt-5 border-t border-slate-100 pt-4">{people.slice(0,3).map(p => <div key={p} className="mb-3 flex items-center gap-2"><Avatar name={p}/><span className="text-xs"><b className="block">{p}</b><span className="text-slate-500">Product · Northstar</span></span></div>)}</div></aside></div> }
function Employees() { return <div className="space-y-6"><PageHead heading="Employees who can refer you" copy="Senior Product Designer at Northstar Labs" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{people.map((p,i) => <Card key={p}><div className="flex items-center gap-3"><Avatar name={p}/><div><h2 className="font-semibold">{p}</h2><p className="text-xs text-slate-500">{i ? "Engineering" : "Product design"} · Northstar Labs</p></div></div><Badge type={i === 3 ? "pending" : "accepted"}>{i === 3 ? "Limited availability" : "Open to referrals"}</Badge><div className="mt-4 flex gap-2"><Link href="/profile/1" className="flex-1 rounded-md border border-slate-200 py-2 text-center text-xs font-semibold">View profile</Link><button className="flex-1 rounded-md bg-primary py-2 text-xs font-semibold text-white">Request</button></div></Card>)}</div></div> }
function Referrals({ role }: { role: Role }) { return <div className="space-y-6"><PageHead heading="Referral requests" copy={role === "employee" ? "Review requests and track the people you have referred." : "Track each referral from introduction to outcome."} /><div className="flex gap-2 border-b border-slate-200">{["All","Pending","Accepted","Completed"].map((x,i) => <button key={x} className={`border-b-2 px-3 py-3 text-sm font-medium ${i === 0 ? "border-primary text-primary" : "border-transparent text-slate-500"}`}>{x}</button>)}</div><Card><ReferralRows interactive={role === "employee"} /></Card></div> }

function ManageJobs({ admin = false }: { admin?: boolean }) { return <ListPage heading={admin ? "All jobs" : "Manage jobs"} copy={admin ? "Review publishing health across every company." : "Create, publish and keep your roles up to date."} action="Create job" href="/jobs/manage/new" columns={admin ? ["Job", "Company", "Status", "Applicants", "Posted"] : ["Job","Status","Applicants","Referrals","Posted"]} rows={jobs.slice(0,3).map((j,i) => admin ? [j.title, j.company, i===2?"Draft":"Open", String(18-i*6), "Aug 28, 2026"] : [j.title, i===2?"Draft":"Open", String(18-i*6), String(j.referrals), "Aug 28, 2026"])} /> }
function Candidates() { return <ListPage heading="Candidates" columns={["Candidate","Job","Source","Stage","Applied"]} rows={people.map((p,i) => [p,jobs[i].title,i===0?"Referral · Ananya":"Direct",["Screening","Interview","Applied","Offer"][i],"Today"])} /> }
function AdminUsers() { return <ListPage heading="Users" action="Invite user" columns={["Name","Role","Company","Status","Joined"]} rows={people.map((p,i) => [p,["Applicant","Employee","Recruiter","Applicant"][i],i===2?"Northstar Labs":"-","Active","Aug 2026"])} /> }
function ListPage({ heading, copy, action, href, columns, rows }: { heading: string; copy?: string; action?: string; href?: string; columns: string[]; rows: string[][] }) { const [query, setQuery] = useState(""); const [filters, setFilters] = useState(false); const visible = rows.filter(row => row.join(" ").toLowerCase().includes(query.toLowerCase())); return <div className="space-y-6"><PageHead heading={heading} copy={copy} action={action} href={href} /><Card><div className="mb-5 flex flex-wrap gap-2"><label className="flex min-w-56 flex-1 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 py-2 focus-within:border-sky-400 focus-within:ring-2 focus-within:ring-sky-100"><Search className="size-4 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-400" placeholder={`Search ${heading.toLowerCase()}`} /></label><button onClick={() => setFilters(!filters)} aria-pressed={filters} className={`rounded-md border px-3 text-xs font-medium ${filters ? "border-sky-300 bg-sky-50 text-primary" : "border-slate-200"}`}>Filters</button></div>{filters && <div className="mb-5 flex flex-wrap gap-2 rounded-md border border-slate-200 bg-slate-50 p-3"><select aria-label="Status" className="rounded border border-slate-200 bg-white px-2 py-1.5 text-xs"><option>All statuses</option><option>Active</option><option>Pending</option></select><select aria-label="Date range" className="rounded border border-slate-200 bg-white px-2 py-1.5 text-xs"><option>All time</option><option>Last 30 days</option></select><button onClick={() => { setQuery(""); setFilters(false); }} className="px-2 text-xs font-semibold text-primary">Reset</button></div>}{visible.length ? <DataTable columns={columns} rows={visible} /> : <Empty text={`No ${heading.toLowerCase()} match your search.`} />}</Card></div> }
function JobForm({ edit }: { edit: boolean }) { const [saved, setSaved] = useState(false); const [published, setPublished] = useState(false); return <div className="space-y-6"><PageHead heading={edit ? "Edit job" : "Create job"} copy="Build a clear, complete posting candidates can trust." extra={<div className="flex gap-2"><button onClick={() => setSaved(true)} className="rounded-md border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Save draft</button><button onClick={() => { setPublished(true); setSaved(true); }} className="rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-white">Publish job</button></div>} />{saved && <div role="status" className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><Check className="size-4" />{published ? "Job published in this demo workspace." : "Draft saved just now."}</div>}<div className="mx-auto max-w-4xl space-y-5"><FormSection title="Basics"><div className="grid gap-4 sm:grid-cols-2"><Field label="Job title" value={edit ? "Senior Product Designer" : ""} placeholder="e.g. Product Designer" /><Field label="Department" value="Product" /><Field label="Location" value="Bengaluru, India" /><Field label="Employment type" value="Full-time" /></div></FormSection><FormSection title="Role details"><Field label="Short summary" value="Lead product discovery and design clear, high-quality hiring experiences." multiline /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Salary range" value="₹28L – ₹38L" /><Field label="Experience level" value="Mid–senior" /></div></FormSection><FormSection title="Requirements"><Field label="Key requirements" value="5+ years in product design\nStrong systems thinking\nExperience with B2B SaaS" multiline /></FormSection><FormSection title="Referral settings"><label className="flex items-start justify-between gap-5 rounded-md bg-slate-50 p-3 text-sm"><span><b className="block">Allow employee referrals</b><span className="mt-1 block text-xs text-slate-500">Employees can share this role with qualified applicants.</span></span><span className="h-6 w-11 rounded-full bg-primary p-1 text-right"><span className="inline-block size-4 rounded-full bg-white" /></span></label></FormSection></div></div> }
function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <Card title={title}>{children}</Card> }
function Field({ label, value, placeholder, multiline = false }: { label: string; value?: string; placeholder?: string; multiline?: boolean }) { return <label className="block text-sm font-medium text-slate-700"><span>{label}</span>{multiline ? <textarea defaultValue={value} placeholder={placeholder} rows={4} className="mt-2 block w-full resize-y rounded-md border border-slate-200 px-3 py-2 text-sm font-normal outline-none focus:border-sky-400 focus:ring-2 focus:ring-sky-100" /> : <input defaultValue={value} placeholder={placeholder} className="mt-2 block w-full rounded-md border border-slate-200 px-3 py-2 text-sm font-normal outline-none focus:border-sky-400 focus:ring-2 focus:ring-sky-100" />}</label> }
function EmployeeProfile() { const [modal, setModal] = useState(false); return <div className="mx-auto max-w-3xl space-y-6"><Link href="/jobs/1/employees" className="inline-flex items-center gap-1 text-sm font-medium text-slate-500 hover:text-primary"><ChevronLeft className="size-4" />Back to employees</Link><Card><div className="flex flex-wrap items-start gap-5"><Avatar name="Ananya Rao" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Ananya Rao</h1><Badge type="accepted">Open to referrals</Badge></div><p className="mt-1 text-sm text-slate-500">Staff Product Designer · Northstar Labs</p><p className="mt-5 max-w-xl text-sm leading-7 text-slate-600">I enjoy helping thoughtful designers learn about the team and make an informed decision. Please include a short note about the work you are looking for.</p><div className="mt-5 flex flex-wrap gap-2">{["Product design", "Research", "Design systems"].map(skill => <span key={skill} className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{skill}</span>)}</div></div></div><div className="mt-6 border-t border-slate-100 pt-5"><button onClick={() => setModal(true)} className="w-full rounded-md bg-primary px-4 py-3 text-sm font-semibold text-white sm:w-auto">Request a referral</button></div></Card>{modal && <ReferralModal onClose={() => setModal(false)} />}</div> }
function ReferralModal({ onClose }: { onClose: () => void }) { const [note, setNote] = useState(""); const [sent, setSent] = useState(false); return <div role="dialog" aria-modal="true" aria-labelledby="request-title" className="fixed inset-0 z-[60] grid place-items-end bg-slate-950/35 p-0 sm:place-items-center sm:p-5"><div className="w-full max-w-xl bg-white shadow-2xl sm:rounded-lg"><div className="flex items-start justify-between border-b border-slate-100 p-5"><div><h2 id="request-title" className="font-semibold">Request a referral</h2><p className="mt-1 text-sm text-slate-500">Senior Product Designer · Northstar Labs</p></div><button aria-label="Close request" onClick={onClose} className="rounded p-1 text-slate-400 hover:bg-slate-100"><X className="size-5" /></button></div>{sent ? <div className="p-8 text-center"><span className="mx-auto grid size-11 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-5" /></span><h3 className="mt-4 font-semibold">Request sent</h3><p className="mt-1 text-sm text-slate-500">Ananya will be notified and you can track the response in Referrals.</p><button onClick={onClose} className="mt-5 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white">Done</button></div> : <div className="p-5"><div className="rounded-md bg-slate-50 p-3 text-sm"><b>To Ananya Rao</b><span className="block text-xs text-slate-500">Staff Product Designer at Northstar Labs</span></div><label className="mt-5 block text-sm font-medium">Add a note <span className="font-normal text-slate-400">(optional but recommended)</span><textarea value={note} onChange={e => setNote(e.target.value.slice(0, 500))} rows={5} placeholder="Briefly introduce yourself and why this role is a good fit." className="mt-2 block w-full resize-none rounded-md border border-slate-200 p-3 text-sm font-normal outline-none focus:border-sky-400 focus:ring-2 focus:ring-sky-100" /><span className="mt-1 block text-right text-xs font-normal text-slate-400">{note.length}/500</span></label><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-md px-4 py-2 text-sm font-semibold">Cancel</button><button onClick={() => setSent(true)} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white">Send request</button></div></div>}</div></div> }
function SavedJobs() { return <div className="space-y-6"><PageHead heading="Saved jobs" copy="Keep promising opportunities close while you decide where to apply." />{jobs.slice(0, 2).length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{jobs.slice(0, 2).map(job => <JobCard key={job.title} job={job} />)}</div> : <Card><Empty text="No saved jobs yet." /></Card>}</div> }
function Messages() { return <div className="space-y-6"><PageHead heading="Messages" copy="A focused place for referral conversations." /><Card><Empty text="No messages yet." /></Card></div> }
function Pipeline() { return <div><PageHead heading="Hiring pipeline" copy="Track candidates across every hiring stage." extra={<select className="rounded-md border border-slate-200 px-3 py-2 text-xs"><option>All jobs</option></select>} /><div className="mt-6 grid min-w-[800px] grid-cols-5 gap-3 overflow-x-auto">{["Applied","Screening","Interview","Offer","Hired"].map((stage,i) => <div key={stage} className="min-h-80 bg-slate-100 p-3"><div className="mb-3 flex justify-between text-xs font-semibold"><span>{stage}</span><span className="rounded-full bg-white px-2">{4-i}</span></div>{people.slice(0,Math.max(1,4-i)).map((p,j) => <div key={p} className="mb-2 border border-slate-200 bg-white p-3"><div className="flex gap-2"><Avatar name={p}/><span className="text-xs"><b className="block">{p}</b>{jobs[(i+j)%jobs.length].title}</span></div>{j===0 && <span className="mt-3 inline-block text-[10px] text-teal-700">Referral candidate</span>}</div>)}</div>)}</div></div> }
function Notifications() { return <div className="space-y-6"><PageHead heading="Notifications" action="Mark all as read" /><Card>{["Your referral request was accepted by Ananya Rao","New matching job: Senior Product Designer at Northstar Labs","Your profile was viewed by a hiring team","Interview scheduled for Frontend Engineer"].map((x,i) => <div className={`flex gap-3 border-b border-slate-100 py-4 last:border-0 ${i<2?"border-l-2 border-l-primary pl-3":""}`} key={x}><Bell className="mt-0.5 size-4 text-primary"/><div><p className="text-sm font-medium">{x}</p><p className="mt-1 text-xs text-slate-400">{i+1}h ago</p></div></div>)}</Card></div> }
function Profile({ role }: { role: Role }) { return <div className="space-y-6"><PageHead heading="Your profile" action="Edit profile" /><Card><div className="flex flex-wrap items-center gap-4"><span className="grid size-20 place-items-center rounded-full bg-sky-100 text-xl font-bold text-sky-700">AR</span><div className="flex-1"><h1 className="text-xl font-semibold">Aarav Rao</h1><p className="text-sm text-slate-500">{role === "employee" ? "Product Designer at Northstar Labs" : role === "recruiter" ? "Talent Partner at Northstar Labs" : "Product Designer"}</p><div className="mt-2 text-xs text-slate-500">Profile 70% complete</div></div><div className="grid size-14 place-items-center rounded-full border-4 border-sky-100 text-xs font-semibold text-primary">70%</div></div></Card><div className="grid gap-6 lg:grid-cols-2"><Card title="Professional information"><div className="space-y-4 text-sm"><p><b className="block">About</b><span className="text-slate-500">Designing clear, useful products for ambitious teams.</span></p><p><b className="block">Skills</b><span className="text-slate-500">Product design · Research · Figma · Systems thinking</span></p></div></Card><Card title="Preferences"><div className="space-y-4 text-sm"><p><b className="block">Profile visibility</b><span className="text-slate-500">Visible to employees and recruiters</span></p><p><b className="block">Notifications</b><span className="text-slate-500">In-app and email enabled</span></p></div></Card></div></div> }
function SettingsPage({ preferences }: { preferences: boolean }) { return <div className="space-y-6"><PageHead heading={preferences ? "Referral preferences" : "Settings"} copy={preferences ? "Control how and when you receive requests." : "Manage account, notification and privacy preferences."} /><Card title={preferences ? "Availability" : "Account settings"}><div className="space-y-5"><label className="flex items-center justify-between text-sm font-medium">{preferences ? "Open to new referral requests" : "Email notifications"}<button className="h-6 w-11 rounded-full bg-primary p-1 text-right"><span className="inline-block size-4 rounded-full bg-white" /></button></label><label className="block text-sm font-medium">{preferences ? "Maximum concurrent requests" : "Profile visibility"}<select className="mt-2 block rounded-md border border-slate-200 px-3 py-2 text-sm"><option>{preferences ? "5 active requests" : "Visible to verified users"}</option></select></label><button className="rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-white">Save changes</button></div></Card></div> }
function Activity() { return <div className="space-y-6"><PageHead heading="Platform activity" copy="A chronological audit trail of meaningful platform events." /><Card>{["Maya Chen accepted a referral request","Northstar Labs posted Frontend Engineer","Ananya Rao joined as an employee","Admin verified a recruiter account"].map((x,i) => <div key={x} className="flex gap-4 border-b border-slate-100 py-4 last:border-0"><span className="font-mono text-xs text-slate-400">10:{42-i*3} AM</span><p className="text-sm">{x}</p></div>)}</Card></div> }
function Reports() { return <div className="space-y-6"><PageHead heading="Reports and analytics" action="Export CSV" /><div className="grid gap-6 md:grid-cols-2"><Chart title="Referral success rate" labels={["Jan","Feb","Mar","Apr","May","Jun"]}/><Chart title="Time to hire" labels={["Direct","Referral"]}/></div><Card title="Top referrers"><DataTable columns={["Employee","Referrals","Hired","Response rate"]} rows={people.map((p,i)=>[p,String(16-i*2),String(9-i),"94%"])}/></Card></div> }
function PageHead({ eyebrow, heading, copy, action, href, extra }: { eyebrow?: string; heading: string; copy?: string; action?: string; href?: string; extra?: React.ReactNode }) { return <div className="flex flex-wrap items-end justify-between gap-4"><div>{eyebrow && <p className="mb-2 text-xs font-semibold uppercase tracking-[.12em] text-primary">{eyebrow}</p>}<h1 className="text-2xl font-semibold tracking-tight">{heading}</h1>{copy && <p className="mt-1 text-sm text-slate-500">{copy}</p>}</div>{extra || (action && <Link href={href || "#"} className="rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-white"><Plus className="mr-1 inline size-4"/>{action}</Link>)}</div> }
function SectionHead({ title, action, href }: { title:string; action:string; href:string }) { return <div className="flex justify-between"><h2 className="text-sm font-semibold">{title}</h2><Link href={href} className="text-xs font-semibold text-primary">{action}</Link></div> }
function Avatar({ name }: { name:string }) { return <span className="grid size-9 shrink-0 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">{name.split(" ").map(x=>x[0]).join("")}</span> }
function ReferralRows({ interactive }: { interactive?: boolean }) { return <div className="divide-y divide-slate-100">{[["Ananya Rao","Senior Product Designer","Accepted","accepted"],["Ishaan Kapoor","Frontend Engineer","In progress","progress"],["Maya Chen","Data Analyst","Pending","pending"]].map(([name,job,status,type]) => <div key={name} className="flex flex-wrap items-center gap-3 py-3 first:pt-0 last:pb-0"><Avatar name={name}/><span className="min-w-40 flex-1 text-sm"><b className="block">{name}</b><small className="text-slate-500">{job} · Northstar Labs</small></span><Badge type={type}>{status}</Badge>{interactive && status === "Pending" && <button className="rounded bg-primary px-2 py-1 text-xs font-semibold text-white">Review</button>}<ChevronRight className="size-4 text-slate-400"/></div>)}</div> }
function ReferralSummary() { return <Card title="Referral requests" action="View all"><ReferralRows /></Card> }
function NotificationsPreview() { return <Card title="Notifications" action="View all"><div className="space-y-3">{["Referral request accepted","New job matches your profile","Profile viewed by a hiring team"].map((x,i)=><div key={x} className="flex gap-2 text-xs"><span className={`mt-1 size-1.5 rounded-full ${i===0?"bg-primary":"bg-slate-300"}`}/><span className="flex-1">{x}<small className="ml-2 text-slate-400">{i+1}h</small></span></div>)}</div></Card> }
function DataTable({ columns, rows }: { columns:string[]; rows:string[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr>{columns.map(x=><th key={x} className="px-2 py-3 font-medium">{x}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-b border-slate-100 hover:bg-slate-50">{r.map((x,j)=><td key={j} className="px-2 py-3">{j===0?<b className="font-medium">{x}</b>: x==="Open"?<Badge type="accepted">Open</Badge>:x==="Draft"?<Badge>Draft</Badge>:x==="Active"?<Badge type="accepted">Active</Badge>:x}</td>)}<td><button aria-label="More actions"><Ellipsis className="size-5 text-slate-400"/></button></td></tr>)}</tbody></table></div> }
function Chart({ title, labels }: { title:string; labels:string[] }) { return <Card title={title}><div className="flex h-48 items-end gap-2 border-b border-slate-200 pb-6">{labels.map((x,i)=><div key={x} className="flex flex-1 flex-col items-center gap-2"><div className="w-full bg-primary/80" style={{height:`${40+i*13}%`}}/><span className="text-[10px] text-slate-400">{x}</span></div>)}</div></Card> }
function Empty({ text = "Nothing to show here yet." }: { text?:string }) { return <div className="grid min-h-40 place-items-center text-center"><div><Sparkles className="mx-auto mb-2 size-5 text-slate-300"/><p className="text-sm font-medium">{text}</p><p className="mt-1 text-xs text-slate-500">When there is activity, it will appear here.</p></div></div> }
function pageTitle(path:string, role:Role) { if(path==="/dashboard") return "Dashboard"; if(path==="/admin") return "Admin dashboard"; const item=nav[role].find(x=>x.href===path); return item?.label || path.split("/").filter(Boolean).pop()?.replace(/-/g," ") || "TrustHire"; }
function withRole(href:string, role:Role) { return `${href}?role=${role}`; }
